services:

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: market_db
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - DB_HOST=db
      - DB_NAME=market_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./pipeline:/opt/airflow/pipeline
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: standalone

volumes:
  pgdata: